/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import java.awt.HeadlessException;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import obligatorio_2.Sistema;
import obligatorio_2.Area;
import obligatorio_2.Area;
import obligatorio_2.Sistema;

public class AltaArea extends javax.swing.JFrame {
    public Sistema sistema;
    
    public AltaArea(Sistema s){
        initComponents();
        this.sistema = s;
        limpiarCampos();
        actualizarLista();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areasRegistradas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPresupuesto = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAreas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Áreas");
        getContentPane().setLayout(null);

        areasRegistradas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areasRegistradas.setText("Áreas Registradas:");
        getContentPane().add(areasRegistradas);
        areasRegistradas.setBounds(30, 30, 130, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 60, 160, 30);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setText("txtNombre");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(340, 90, 280, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Descripción:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 130, 160, 20);

        txtDescripcion.setText("txtDescripcion");
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(340, 160, 280, 90);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Presupuesto Anual (US$):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 260, 170, 20);

        txtPresupuesto.setText("txtPresupuesto");
        txtPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPresupuesto);
        txtPresupuesto.setBounds(340, 290, 280, 30);

        btnAgregar.setText("Agregar Área");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(340, 360, 120, 30);

        lstAreas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAreas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 250, 330);

        setSize(new java.awt.Dimension(669, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresupuestoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      guardarArea();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void guardarArea() {
        try {
            // Validar que los campos no estén vacíos
            if (txtNombre.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (txtDescripcion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (txtPresupuesto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El presupuesto no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validar que el presupuesto sea un número válido
            double presupuesto;
            try {
                presupuesto = Double.parseDouble(txtPresupuesto.getText().trim());
                if (presupuesto <= 0) {
                    JOptionPane.showMessageDialog(this, "El presupuesto debe ser mayor a 0", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "El presupuesto debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Crear el área y agregarla al sistema
            Area nuevaArea = new Area(
                txtNombre.getText().trim(), 
                txtDescripcion.getText().trim(), 
                presupuesto
            );
            
            sistema.getListaAreas().add(nuevaArea);
            
            JOptionPane.showMessageDialog(this, 
                "Área '" + nuevaArea.getNombre() + "' creada exitosamente!\n" +
                "Presupuesto: US$ " + nuevaArea.getPresupuesto(), 
                "Área Guardada", 
                JOptionPane.INFORMATION_MESSAGE);
            actualizarLista();
            limpiarCampos();
            
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void actualizarLista() {
        // Obtener la lista del sistema
        java.util.ArrayList<Area> lista = sistema.getListaAreas();

        // Ordenar por nombre creciente (Requisito del PDF )
        Collections.sort(lista, new Comparator<Area>() {
            @Override
            public int compare(Area o1, Area o2) {
                return o1.getNombre().compareToIgnoreCase(o2.getNombre());
            }
        });

        // Pasar los datos al JList visual
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Area a : lista) {
            // Mostrar Nombre - Descripción (o lo que prefieras)
            listModel.addElement(a.getNombre() + " (" + a.getPresupuesto() + ")");
        }
        lstAreas.setModel(listModel);
    }
    
    private void limpiarCampos() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtPresupuesto.setText("");
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areasRegistradas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstAreas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPresupuesto;
    // End of variables declaration//GEN-END:variables
}
