/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import obligatorio_2.Sistema;
import obligatorio_2.Empleado;
import obligatorio_2.Manager;
import obligatorio_2.Area;
import obligatorio_2.ArchivoGrabacion;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Roy
 */
public class AltaEmpleado extends javax.swing.JFrame {
    private Sistema sistema;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AltaEmpleado.class.getName());
    
    /**
     * Creates new form AltaEmpleado
     */
    public AltaEmpleado(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        
        configurarInterfaz();
        actualizarListaEmpleados();
        cargarComboBoxes();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpleados = new javax.swing.JList<>();
        areasRegistradas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCurriculum = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox<>();
        comboManager = new javax.swing.JComboBox<>();
        areasRegistradas1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lstEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEmpleadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmpleados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 290, 270);

        areasRegistradas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        areasRegistradas.setText("Detalles empleado:");
        getContentPane().add(areasRegistradas);
        areasRegistradas.setBounds(20, 340, 190, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 30, 160, 30);

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedula);
        txtCedula.setBounds(340, 130, 280, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Área:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 510, 160, 20);

        txtCurriculum.setColumns(20);
        txtCurriculum.setRows(5);
        jScrollPane2.setViewportView(txtCurriculum);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 270, 280, 100);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Salario Mensual (US$):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 380, 170, 20);

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        getContentPane().add(txtCelular);
        txtCelular.setBounds(340, 200, 280, 30);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar Empleado");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(340, 600, 150, 30);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(500, 600, 120, 30);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(340, 60, 280, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cédula:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 100, 160, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 170, 160, 20);

        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalario);
        txtSalario.setBounds(340, 410, 280, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Currículum:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 240, 160, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Manager:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 450, 160, 20);

        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboArea);
        comboArea.setBounds(340, 540, 280, 22);

        comboManager.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboManager);
        comboManager.setBounds(340, 480, 280, 22);

        areasRegistradas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        areasRegistradas1.setText("Empleados Registrados:");
        getContentPane().add(areasRegistradas1);
        areasRegistradas1.setBounds(20, 30, 190, 20);

        txtDetalles.setEditable(false);
        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane3.setViewportView(txtDetalles);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 370, 290, 260);

        setSize(new java.awt.Dimension(666, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarEmpleado();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void lstEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEmpleadosValueChanged
        if (!evt.getValueIsAdjusting() && lstEmpleados.getSelectedIndex() != -1) {
            int selectedIndex = lstEmpleados.getSelectedIndex();
            if (selectedIndex >= 0 && selectedIndex < sistema.getListaEmpleados().size()) {
                Empleado empleadoSeleccionado = sistema.getListaEmpleados().get(selectedIndex);
                mostrarDetallesEmpleado(empleadoSeleccionado);
            }
        }
    }//GEN-LAST:event_lstEmpleadosValueChanged
    
    
    //Para que haga salto de linea automatico al escribir , sino sigue de largo y no se lee.
    private void configurarInterfaz() {
        txtCurriculum.setLineWrap(true);
        txtCurriculum.setWrapStyleWord(true);
        
        txtDetalles.setLineWrap(true);
        txtDetalles.setWrapStyleWord(true);
    }
    
    private void actualizarListaEmpleados() {
        java.util.ArrayList<Empleado> listaEmpleados = sistema.getListaEmpleados();
        
        // Ordenar por salario creciente
        Collections.sort(listaEmpleados, new Comparator<Empleado>() {
            @Override
            public int compare(Empleado e1, Empleado e2) {
                return Double.compare(e1.getSalarioMensual(), e2.getSalarioMensual());
            }
        });
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Empleado empleado : listaEmpleados) {
            listModel.addElement(empleado.getNombre() + " - US$ " + empleado.getSalarioMensual());
        }
        lstEmpleados.setModel(listModel);
    }
    
    private void cargarComboBoxes() {
        // Cargar managers
        DefaultComboBoxModel<String> modelManager = new DefaultComboBoxModel<>();
        for (Manager manager : sistema.getListaManagers()) {
            modelManager.addElement(manager.getNombre() + " - " + manager.getCedula());
        }
        comboManager.setModel(modelManager);
        
        // Cargar áreas
        DefaultComboBoxModel<String> modelArea = new DefaultComboBoxModel<>();
        for (Area area : sistema.getListaAreas()) {
            modelArea.addElement(area.getNombre());
        }
        comboArea.setModel(modelArea);
    }
    
    private void mostrarDetallesEmpleado(Empleado empleado) {
        StringBuilder detalles = new StringBuilder();
        detalles.append("Nombre: ").append(empleado.getNombre()).append("\n");
        detalles.append("Cédula: ").append(empleado.getCedula()).append("\n");
        detalles.append("Celular: ").append(empleado.getCelular()).append("\n");
        detalles.append("Salario: US$ ").append(empleado.getSalarioMensual()).append("\n");
        detalles.append("Manager: ").append(empleado.getManager().getNombre()).append("\n");
        detalles.append("Área: ").append(empleado.getArea().getNombre()).append("\n");
        detalles.append("Currículum: ").append(empleado.getCurriculum());
        
        txtDetalles.setText(detalles.toString());
    }
    
    private void agregarEmpleado() {
        try {
            // Validar campos obligatorios
            if (txtNombre.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (txtCedula.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La cédula no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (txtCelular.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El celular no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (txtCurriculum.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El currículum no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (txtSalario.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El salario no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validar cédula única
            String cedula = txtCedula.getText().trim();
            if (!sistema.validarNombreUnico(cedula, "EMPLEADO")) {
                JOptionPane.showMessageDialog(this, "La cédula ya existe en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validar salario
            double salario;
            try {
                salario = Double.parseDouble(txtSalario.getText().trim());
                if (salario <= 0) {
                    JOptionPane.showMessageDialog(this, "El salario debe ser mayor a 0", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "El salario debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Obtener manager y área seleccionados
            if (comboManager.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un manager", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (comboArea.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un área", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Manager managerSeleccionado = sistema.getListaManagers().get(comboManager.getSelectedIndex());
            Area areaSeleccionada = sistema.getListaAreas().get(comboArea.getSelectedIndex());
            
            // Validar presupuesto del área (salario anual = salario * 12)
            double salarioAnual = salario * 12;
            if (salarioAnual > areaSeleccionada.getPresupuesto()) {
                JOptionPane.showMessageDialog(this, 
                    "El área '" + areaSeleccionada.getNombre() + "' no tiene presupuesto suficiente.\n" +
                    "Presupuesto disponible: US$ " + areaSeleccionada.getPresupuesto() + "\n" +
                    "Salario anual requerido: US$ " + salarioAnual,
                    "Error de Presupuesto", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Crear empleado
            Empleado nuevoEmpleado = new Empleado(
                txtNombre.getText().trim(),
                cedula,
                txtCelular.getText().trim(),
                txtCurriculum.getText().trim(),
                salario,
                managerSeleccionado,
                areaSeleccionada
            );
            
            // Actualizar presupuesto del área
            areaSeleccionada.setPresupuesto(areaSeleccionada.getPresupuesto() - salarioAnual);
            
            // Agregar empleado al sistema
            sistema.getListaEmpleados().add(nuevoEmpleado);
            
            // Guardar currículum en archivo
            guardarCurriculum(cedula, txtCurriculum.getText().trim());
            
            JOptionPane.showMessageDialog(this,
                "Empleado '" + nuevoEmpleado.getNombre() + "' agregado exitosamente\n" +
                "Currículum guardado en: cvs/CV" + cedula + ".txt",
                "Empleado Agregado",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar campos y actualizar lista
            limpiarCampos();
            actualizarListaEmpleados();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Error al agregar empleado: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void guardarCurriculum(String cedula, String curriculum) {
        try {
            // Crear directorio cvs si no existe
            File directorio = new File("cvs");
            if (!directorio.exists()) {
                directorio.mkdir();
            }
            
            // Crear archivo usando ArchivoGrabacion
            String nombreArchivo = "cvs/CV" + cedula + ".txt";
            ArchivoGrabacion archivo = new ArchivoGrabacion(nombreArchivo, false); // false para sobreescribir si existe
            
            // Grabar el currículum línea por línea (o todo en una línea)
            // Si el curriculum tiene múltiples líneas, las separamos
            String[] lineas = curriculum.split("\n");
            for (String linea : lineas) {
                archivo.grabarLinea(linea);
            }
            
            archivo.cerrar();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al guardar el currículum: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpiarCampos() {
        txtNombre.setText("");
        txtCedula.setText("");
        txtCelular.setText("");
        txtCurriculum.setText("");
        txtSalario.setText("");
        txtDetalles.setText("");
    }
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areasRegistradas;
    private javax.swing.JLabel areasRegistradas1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboArea;
    private javax.swing.JComboBox<String> comboManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstEmpleados;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextArea txtCurriculum;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
