/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import obligatorio_2.Sistema;
import obligatorio_2.Area;
import obligatorio_2.Empleado;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rsuarez
 */
public class BajaArea extends javax.swing.JFrame {
    private Sistema sistema;
    private Area areaSeleccionada;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BajaArea.class.getName());

    /**
     * Creates new form BajaArea
     */
    public BajaArea(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        this.areaSeleccionada = null;
        btnEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtPresupuesto = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAreas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Áreas Registradas (sin empleados):");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 250, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 60, 80, 20);

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(340, 90, 280, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 130, 110, 20);

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(340, 160, 280, 100);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Presupuesto Anual (US$):");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 270, 170, 20);

        txtPresupuesto.setEditable(false);
        getContentPane().add(txtPresupuesto);
        txtPresupuesto.setBounds(340, 300, 280, 30);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar Área");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(340, 360, 150, 30);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(500, 360, 120, 30);

        lstAreas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstAreas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAreas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAreasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstAreas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 250, 330);

        setSize(new java.awt.Dimension(666, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstAreasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAreasValueChanged
        if (!evt.getValueIsAdjusting() && lstAreas.getSelectedIndex() != -1) {
            int selectedIndex = lstAreas.getSelectedIndex();
            java.util.ArrayList<Area> areasSinEmpleados = obtenerAreasSinEmpleados();
            
            if (selectedIndex >= 0 && selectedIndex < areasSinEmpleados.size()) {
                areaSeleccionada = areasSinEmpleados.get(selectedIndex);
                cargarDatosArea();
                btnEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_lstAreasValueChanged

    private void actualizarListaAreas() {
        java.util.ArrayList<Area> areasSinEmpleados = obtenerAreasSinEmpleados();
        
        // Ordenar por nombre creciente
        Collections.sort(areasSinEmpleados, new Comparator<Area>() {
            @Override
            public int compare(Area o1, Area o2) {
                return o1.getNombre().compareToIgnoreCase(o2.getNombre());
            }
        });
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Area area : areasSinEmpleados) {
            listModel.addElement(area.getNombre());
        }
        lstAreas.setModel(listModel);
        
        // Limpiar selección y datos
        areaSeleccionada = null;
        limpiarCampos();
        btnEliminar.setEnabled(false);
    }
    
    private java.util.ArrayList<Area> obtenerAreasSinEmpleados() {
        java.util.ArrayList<Area> areasSinEmpleados = new java.util.ArrayList<>();
        java.util.ArrayList<Area> todasLasAreas = sistema.getListaAreas();

        for (Area area : todasLasAreas) {
            boolean tieneEmpleados = false;

            // Verificar si algún empleado está en esta área
            for (Empleado empleado : sistema.getListaEmpleados()) {
                if (empleado.getArea().equals(area)) {
                    tieneEmpleados = true;
                    break;
                }
            }

            if (!tieneEmpleados) {
                areasSinEmpleados.add(area);
            }
        }

        return areasSinEmpleados;
    }
        
    private void cargarDatosArea() {
        if (areaSeleccionada != null) {
            txtNombre.setText(areaSeleccionada.getNombre());
            txtDescripcion.setText(areaSeleccionada.getDescripcion());
            txtPresupuesto.setText(String.format("US$ %.2f", areaSeleccionada.getPresupuesto()));
        }
    }
    
    private void limpiarCampos() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtPresupuesto.setText("");
    }
    
    private void eliminarArea() {
        if (areaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, 
                "Por favor seleccione un área para eliminar", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirmar eliminación
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de que desea eliminar el área '" + areaSeleccionada.getNombre() + "'?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Eliminar el área del sistema
            sistema.getListaAreas().remove(areaSeleccionada);
            
            JOptionPane.showMessageDialog(this,
                "Área '" + areaSeleccionada.getNombre() + "' eliminada exitosamente",
                "Área Eliminada",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Actualizar la lista
            actualizarListaAreas();
        }
    }
    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarArea();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstAreas;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPresupuesto;
    // End of variables declaration//GEN-END:variables
}
