/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import obligatorio_2.Sistema;
import obligatorio_2.Area;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rsuarez
 */
public class ModificarArea extends javax.swing.JFrame {
    private Sistema sistema;
    private Area areaSeleccionada;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificarArea.class.getName());

    /**
     * Creates new form ModificarArea
     */
    public ModificarArea(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        this.areaSeleccionada = null;
        
        btnModificar.setEnabled(false);
        actualizarListaAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAreas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPresupuesto = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Áreas");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Áreas Registradas:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 140, 16);

        lstAreas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstAreas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAreas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAreasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstAreas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 250, 330);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 60, 80, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 130, 110, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Presupuesto Anual (US$):");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 270, 170, 20);

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(340, 90, 280, 30);

        txtPresupuesto.setEditable(false);
        getContentPane().add(txtPresupuesto);
        txtPresupuesto.setBounds(340, 300, 280, 30);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(500, 360, 120, 30);

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModificar.setText("Modificar Área");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(340, 360, 150, 30);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 160, 280, 100);

        setSize(new java.awt.Dimension(666, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        guardarCambios();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void lstAreasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAreasValueChanged
        if (!evt.getValueIsAdjusting() && lstAreas.getSelectedIndex() != -1) {
            int selectedIndex = lstAreas.getSelectedIndex();
            if (selectedIndex >= 0 && selectedIndex < sistema.getListaAreas().size()) {
                areaSeleccionada = sistema.getListaAreas().get(selectedIndex);
                cargarDatosArea();
                btnModificar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_lstAreasValueChanged
    
    private void actualizarListaAreas() {
        java.util.ArrayList<Area> lista = sistema.getListaAreas();
        
        // Ordenar por nombre creciente
        Collections.sort(lista, new Comparator<Area>() {
            @Override
            public int compare(Area o1, Area o2) {
                return o1.getNombre().compareToIgnoreCase(o2.getNombre());
            }
        });
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (Area area : lista) {
            listModel.addElement(area.getNombre());
        }
        lstAreas.setModel(listModel);
    }
     
    private void cargarDatosArea() {
        if (areaSeleccionada != null) {
            txtNombre.setText(areaSeleccionada.getNombre());
            txtDescripcion.setText(areaSeleccionada.getDescripcion());
            txtPresupuesto.setText(String.valueOf(areaSeleccionada.getPresupuesto()));
        }
    }
    
    private void guardarCambios() {
        if (areaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un área", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String nuevaDescripcion = txtDescripcion.getText().trim();
        
        if (nuevaDescripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        areaSeleccionada.setDescripcion(nuevaDescripcion);
        
        JOptionPane.showMessageDialog(this, 
            "Descripción del área '" + areaSeleccionada.getNombre() + "' actualizada exitosamente",
            "Cambios Guardados", 
            JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstAreas;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPresupuesto;
    // End of variables declaration//GEN-END:variables
}
