/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import obligatorio_2.Sistema;
import obligatorio_2.Area;
import obligatorio_2.Empleado;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Roy
 */
public class RealizarMovimiento extends javax.swing.JFrame {
    private Sistema sistema;
    private Area areaOrigen;
    private Area areaDestino;
    private Empleado empleado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RealizarMovimiento.class.getName());

    /**
     * Creates new form RealizarMovimiento
     * @param sistema
     */
    public RealizarMovimiento(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        this.areaOrigen = null;
        this.areaDestino = null;
        this.empleado = null;
        
        configurarInterfaz();
        cargarDatosIniciales();
        cargarEmpleadosAreaOrigen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboAreaDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpleados = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        comboAreaOrigen = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        tbnCerrar = new javax.swing.JButton();
        btnRealizarMovimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar Movimiento de Empleado");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Información del movimiento:");

        comboAreaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAreaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaDestinoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Área de destino:");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Área de origen:");

        lstEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEmpleadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmpleados);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mes del movimiento:");

        comboAreaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAreaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaOrigenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Empleados en el Área:");

        txtInformacion.setEditable(false);
        txtInformacion.setColumns(20);
        txtInformacion.setRows(5);
        jScrollPane2.setViewportView(txtInformacion);

        tbnCerrar.setText("Cerrar");
        tbnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnCerrarActionPerformed(evt);
            }
        });

        btnRealizarMovimiento.setText("Realizar Movimiento");
        btnRealizarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(comboAreaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(comboAreaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnRealizarMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tbnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAreaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAreaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRealizarMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_tbnCerrarActionPerformed

    private void btnRealizarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarMovimientoActionPerformed
        realizarMovimiento();
    }//GEN-LAST:event_btnRealizarMovimientoActionPerformed

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        actualizarInformacion();
    }//GEN-LAST:event_comboMesActionPerformed

    private void comboAreaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaOrigenActionPerformed
        cargarEmpleadosAreaOrigen();
        actualizarInformacion();
    }//GEN-LAST:event_comboAreaOrigenActionPerformed

    private void comboAreaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaDestinoActionPerformed
        actualizarInformacion();
    }//GEN-LAST:event_comboAreaDestinoActionPerformed

    private void lstEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEmpleadosValueChanged
        if (!evt.getValueIsAdjusting() && lstEmpleados.getSelectedIndex() != -1) {
            int selectedIndex = lstEmpleados.getSelectedIndex();
            if (areaOrigen != null) {
                java.util.ArrayList<Empleado> empleadosArea = sistema.getEmpleadosPorArea(areaOrigen);
                if (selectedIndex >= 0 && selectedIndex < empleadosArea.size()) {
                    empleado = empleadosArea.get(selectedIndex);
                    actualizarInformacion();
                }
            }
        }       
    }//GEN-LAST:event_lstEmpleadosValueChanged
    
    private void configurarInterfaz() {
        txtInformacion.setEditable(false);
        txtInformacion.setLineWrap(true);
        txtInformacion.setWrapStyleWord(true);
        
        btnRealizarMovimiento.setEnabled(false);
    }
    
    private void cargarDatosIniciales() {
        cargarMeses();
        cargarAreas();
        lstEmpleados.clearSelection();
    }
    
    private void cargarMeses() {
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
                         "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre"};
        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(meses));
    }
    
    private void cargarAreas() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Area area : sistema.getListaAreas()) {
            model.addElement(area.getNombre());
        }
        comboAreaOrigen.setModel(model);
        comboAreaDestino.setModel(model);
    }
    
    private void cargarEmpleadosAreaOrigen() {
        int selectedIndex = comboAreaOrigen.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < sistema.getListaAreas().size()) {
            areaOrigen = sistema.getListaAreas().get(selectedIndex);
            java.util.ArrayList<Empleado> empleadosArea = sistema.getEmpleadosPorArea(areaOrigen);
            
            DefaultListModel<String> listModel = new DefaultListModel<>();
            for (Empleado empleado : empleadosArea) {
                listModel.addElement(empleado.getNombre() + " - US$ " + empleado.getSalarioMensual());
            }
            lstEmpleados.setModel(listModel);
            
            // Limpiar selección de empleado
            empleado = null;
            lstEmpleados.clearSelection();
        }
    }
    
    private void actualizarInformacion() {
        // Deshabilitar botón por defecto
        btnRealizarMovimiento.setEnabled(false);

        // Verificar que todos los campos estén seleccionados
        if (comboMes.getSelectedIndex() == -1 || 
            areaOrigen == null || 
            empleado == null || 
            comboAreaDestino.getSelectedIndex() == -1) {

            txtInformacion.setText("Complete todos los campos para ver la información del movimiento.");
            return;
        }
        int mes = comboMes.getSelectedIndex() + 1; 
        int selectedIndexDestino = comboAreaDestino.getSelectedIndex();
        areaDestino = sistema.getListaAreas().get(selectedIndexDestino);

        // Validar que no sea la misma área
        if (areaOrigen.equals(areaDestino)) {
            txtInformacion.setText("ERROR: El área de origen y destino no pueden ser la misma.");
            return;
        }  
            double salarioRestante = empleado.calcularSalarioRestante(mes);
        double reintegroOrigen = salarioRestante; // El reintegro es igual al salario restante
        double costoDestino = salarioRestante;    // El costo es igual al salario restante
        
        // Verificar si el movimiento es posible
        boolean movimientoPosible = areaDestino.puedeAceptarSalario(costoDestino);
        
        StringBuilder info = new StringBuilder();
        info.append("INFORMACIÓN DEL MOVIMIENTO\n\n");
        
        info.append("EMPLEADO:\n");
        info.append("   • Nombre: ").append(empleado.getNombre()).append("\n");
        info.append("   • Salario mensual: US$ ").append(empleado.getSalarioMensual()).append("\n");
        info.append("   • Meses restantes: ").append(13 - mes).append("\n");
        info.append("   • Salario restante: US$ ").append(String.format("%.2f", salarioRestante)).append("\n\n");
        
        info.append("ÁREA ORIGEN: ").append(areaOrigen.getNombre()).append("\n");
        info.append("   • Presupuesto total: US$ ").append(String.format("" + areaOrigen.getPresupuesto())).append("\n");
        info.append("   • Presupuesto utilizado: US$ ").append(String.format("%.2f" + areaOrigen.getPresupuestoUtilizado())).append("\n");
        info.append("   • Reintegro por movimiento: US$ ").append(String.format("%.2f", reintegroOrigen)).append("\n");
        info.append("   • Nuevo presupuesto utilizado: US$ ").append(String.format("%.2f", (areaOrigen.getPresupuestoUtilizado() - reintegroOrigen))).append("\n\n");
        
        info.append("ÁREA DESTINO: ").append(areaDestino.getNombre()).append("\n");
        info.append("   • Presupuesto total: US$ ").append(String.format("%.2f", areaDestino.getPresupuesto())).append("\n");
        info.append("   • Presupuesto utilizado: US$ ").append(String.format("%.2f", areaDestino.getPresupuestoUtilizado())).append("\n");
        info.append("   • Costo por movimiento: US$ ").append(String.format("%.2f", costoDestino)).append("\n");
        info.append("   • Nuevo presupuesto utilizado: US$ ").append(String.format("%.2f" + areaDestino.getPresupuestoUtilizado() + costoDestino)).append("\n");
        info.append("   • Presupuesto disponible actual: US$ ").append(String.format("%.2f", areaDestino.getPresupuestoDisponible())).append("\n\n");
        
        if (movimientoPosible) {
            info.append("✅ MOVIMIENTO POSIBLE\n");
            info.append("El área destino tiene presupuesto suficiente para aceptar el empleado.");
            btnRealizarMovimiento.setEnabled(true);
        } else {
            info.append("❌ MOVIMIENTO NO POSIBLE\n");
            info.append("El área destino NO tiene presupuesto suficiente.");
            btnRealizarMovimiento.setEnabled(false);
        }
        
        txtInformacion.setText(info.toString());
    }
    
    private void realizarMovimiento() {
        // Validaciones finales
        if (comboMes.getSelectedIndex() == -1 || 
            areaOrigen == null || 
            empleado == null || 
            areaDestino == null) {
            
            JOptionPane.showMessageDialog(this, 
                "Complete todos los campos antes de realizar el movimiento.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int mes = comboMes.getSelectedIndex() + 1;
        
        // Confirmar movimiento
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de realizar el movimiento?\n\n" +
            "Empleado: " + empleado.getNombre() + "\n" +
            "Del área: " + areaOrigen.getNombre() + "\n" +
            "Al área: " + areaDestino.getNombre() + "\n" +
            "A partir del mes: " + comboMes.getSelectedItem() + "\n\n" +
            "Este movimiento actualizará los presupuestos de ambas áreas.",
            "Confirmar Movimiento",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            boolean exito = sistema.realizarMovimiento(empleado, areaDestino, mes);
            
            if (exito) {
                JOptionPane.showMessageDialog(this,
                    "✅ Movimiento realizado exitosamente\n\n" +
                    "Empleado: " + empleado.getNombre() + "\n" +
                    "Se movió de " + areaOrigen.getNombre() + " a " + areaDestino.getNombre() + "\n" +
                    "A partir de: " + comboMes.getSelectedItem() + "\n\n" +
                    "Los presupuestos han sido actualizados automáticamente.",
                    "Movimiento Completado",
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Actualizar interfaz
                cargarEmpleadosAreaOrigen(); // Actualizar lista de empleados
                actualizarInformacion();     // Actualizar información
                
            } else {
                JOptionPane.showMessageDialog(this,
                    "❌ No se pudo realizar el movimiento.\n\n" +
                    "Posibles causas:\n" +
                    "• El área destino ya no tiene presupuesto suficiente\n" +
                    "• Error en el sistema\n" +
                    "Verifique los datos e intente nuevamente.",
                    "Error en Movimiento",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarMovimiento;
    private javax.swing.JComboBox<String> comboAreaDestino;
    private javax.swing.JComboBox<String> comboAreaOrigen;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstEmpleados;
    private javax.swing.JButton tbnCerrar;
    private javax.swing.JTextArea txtInformacion;
    // End of variables declaration//GEN-END:variables
}
