/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author Br1
 */
public class seleccionPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(seleccionPrincipal.class.getName());

    /**
     * Creates new form seleccionPrincpail
     */
    public seleccionPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnGuardado = new javax.swing.JButton();
        btnPrecargados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comenzar con...");
        getContentPane().setLayout(null);

        btnNuevo.setText("Sistema nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevo(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(60, 60, 210, 70);

        btnGuardado.setText("Sistema guardado");
        btnGuardado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardado(evt);
            }
        });
        btnGuardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardado);
        btnGuardado.setBounds(360, 60, 210, 70);

        btnPrecargados.setText("Sistema con datos precargados");
        btnPrecargados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrecargados(evt);
            }
        });
        btnPrecargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecargadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrecargados);
        btnPrecargados.setBounds(650, 60, 210, 70);

        setSize(new java.awt.Dimension(959, 204));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardadoActionPerformed

    private void btnNuevo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevo
        this.dispose();
        new VentanaPrincipal("Nuevo").setVisible(true);
    }//GEN-LAST:event_btnNuevo

    private void btnGuardado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardado
        this.dispose();
        new VentanaPrincipal("Guardado").setVisible(true);
    }//GEN-LAST:event_btnGuardado

    private void btnPrecargados(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrecargados
        this.dispose();
        new VentanaPrincipal("Precargados").setVisible(true);
    }//GEN-LAST:event_btnPrecargados

    private void btnPrecargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecargadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrecargadosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardado;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrecargados;
    // End of variables declaration//GEN-END:variables
}
