/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package interfaz;
import obligatorio_2.Sistema;
/**
 *
 * @author Br1
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    Sistema sistema=new Sistema();

    /**
     * Creates new form VentanaPrinciapal
     */
    public VentanaPrincipal(String seleccion) {
        initComponents();
        
        switch (seleccion) {
        case "Nuevo":
            sistema.limpiarSistema();
            System.out.println("Sistema iniciado: Nuevo (vacío)");
            break;
            
        case "Guardado":
            sistema.cargarDatosGuardados();
            System.out.println("Sistema iniciado: Desde archivo guardado");
            break;
            
        case "Precargados":
            sistema.cargarDatosPrecargados();
            System.out.println("Sistema iniciado: Con datos precargados");
            break;
            
        default:
            sistema.limpiarSistema();
            break;
        }
        
        configurarCierreAutomatico();
    }

    private void configurarCierreAutomatico() {
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                guardarDatosAntesDeCerrar();
            }
        });
    }
    
    private void guardarDatosAntesDeCerrar() {
        try {
            sistema.guardarDatosFinales();
            System.out.println("Datos guardados automáticamente antes de cerrar");
        } catch (Exception e) {
            System.out.println("Error al guardar datos: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        altaEmpleado = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        aboutMenuItem1 = new javax.swing.JMenuItem();
        aboutMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        modificarArea = new javax.swing.JMenu();
        altaArea = new javax.swing.JMenuItem();
        bajaArea = new javax.swing.JMenuItem();
        btnModificarArea = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cortex ERP");

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/logo.png"))); // NOI18N

        editMenu.setMnemonic('e');
        editMenu.setText("Managers");

        cutMenuItem.setText("Alta");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaManager(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Baja");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaManagerActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Modificación");
        editMenu.add(pasteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Empleados");

        altaEmpleado.setText("Alta");
        altaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaEmpleadoActionPerformed(evt);
            }
        });
        helpMenu.add(altaEmpleado);

        menuBar.add(helpMenu);

        jMenu1.setText("Reportes");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        aboutMenuItem1.setText("Report inteligente");
        jMenu1.add(aboutMenuItem1);

        aboutMenuItem2.setText("Reporte de estado de áreas");
        aboutMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(aboutMenuItem2);

        jMenuItem1.setText("Reporte de movimientos");
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        modificarArea.setText("Áreas");
        modificarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAreaActionPerformed(evt);
            }
        });

        altaArea.setText("Alta");
        altaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAreaActionPerformed(evt);
            }
        });
        modificarArea.add(altaArea);

        bajaArea.setText("Baja");
        bajaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaAreaActionPerformed(evt);
            }
        });
        modificarArea.add(bajaArea);

        btnModificarArea.setText("Modificación");
        btnModificarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAreaActionPerformed(evt);
            }
        });
        modificarArea.add(btnModificarArea);

        exitMenuItem.setText("Realizar movimientos");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarMovimiento(evt);
            }
        });
        modificarArea.add(exitMenuItem);

        menuBar.add(modificarArea);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(589, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RealizarMovimiento(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarMovimiento
        ReporteMovimientos realizarMovimiento = new ReporteMovimientos(this.sistema);
        realizarMovimiento.setVisible(true);
    }//GEN-LAST:event_RealizarMovimiento

    private void altaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAreaActionPerformed
        AltaArea ventanaAlta = new AltaArea(this.sistema);
        ventanaAlta.setVisible(true);
    }//GEN-LAST:event_altaAreaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void aboutMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItem2ActionPerformed

    private void altaManager(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaManager
         
        AltaManager ventanaAltaManager= new AltaManager(sistema);
        ventanaAltaManager.setVisible(true);
    }//GEN-LAST:event_altaManager

    private void modificarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAreaActionPerformed

    }//GEN-LAST:event_modificarAreaActionPerformed

    private void btnModificarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAreaActionPerformed
        ModificarArea ventanaModificarArea = new ModificarArea(this.sistema);
        ventanaModificarArea.setVisible(true);
    }//GEN-LAST:event_btnModificarAreaActionPerformed

    private void bajaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaAreaActionPerformed
        BajaArea ventanaBaja = new BajaArea(this.sistema);
        ventanaBaja.setVisible(true);
    }//GEN-LAST:event_bajaAreaActionPerformed

    private void altaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaEmpleadoActionPerformed
        AltaEmpleado ventanaAlta = new AltaEmpleado(this.sistema);
        ventanaAlta.setVisible(true);
    }//GEN-LAST:event_altaEmpleadoActionPerformed

    private void BajaManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaManagerActionPerformed
        BajaManager bajaManager = new BajaManager(this.sistema);
        bajaManager.setVisible(true);
    }//GEN-LAST:event_BajaManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem1;
    private javax.swing.JMenuItem aboutMenuItem2;
    private javax.swing.JMenuItem altaArea;
    private javax.swing.JMenuItem altaEmpleado;
    private javax.swing.JMenuItem bajaArea;
    private javax.swing.JMenuItem btnModificarArea;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu modificarArea;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
